### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by francopestilli** [brainlife/app-sift2-connectome-generation#2]
https://github.com/brainlife/app-sift2-connectome-generation/blob/9761395d86f363597d4a963b0e59076e8c0afa57/generate-connectomes.sh#L143

This is a bug. 

`cp ./connectomes/length.csv ./denlen_out/csv/correlation.csv` >-->> should be>-->>  `cp ./connectomes/denlen.csv ./denlen_out/csv/correlation.csv`

@bacaron

**Comment by bacaron** [comment]
@francopestilli thank you for catching this! i've corrected it in the all the branches affected by it.
